# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Barebones < Formula
  desc "Ultra-fast static HTTP server with metrics."
  homepage "https://github.com/alexlokshin/barebones"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.5.0/barebones_0.5.0_darwin_amd64.tar.gz"
      sha256 "ba9b1ec76c0f2952f2b1e76c583869f36985093bc08ec35cfca296c61bfb4648"

      def install
        bin.install "barebones"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.5.0/barebones_0.5.0_darwin_arm64.tar.gz"
      sha256 "a5fe9dee0e0d9375673ddcd738e234a51b46a8c37448b6ddc9d2d91a421311fe"

      def install
        bin.install "barebones"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.5.0/barebones_0.5.0_linux_amd64.tar.gz"
      sha256 "2328b53f764ed6183b480431bd74306e00999948fd436595b8039c25e0309741"
      def install
        bin.install "barebones"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.5.0/barebones_0.5.0_linux_arm64.tar.gz"
      sha256 "ee26fb57bd14af19bf330e439b001aa7fdf1520f937f363a2eec90a0551002dc"
      def install
        bin.install "barebones"
      end
    end
  end

  test do
    system "#{bin}/barebones", "-health-check"
  end
end
