# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Barebones < Formula
  desc "Ultra-fast static HTTP server with metrics."
  homepage "https://github.com/alexlokshin/barebones"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.4.6/barebones_0.4.6_darwin_amd64.tar.gz"
      sha256 "7e5f0d8b1f230ae828f9738779300e1e006281b6e3c808027d23b8e39015762d"

      def install
        bin.install "barebones"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.4.6/barebones_0.4.6_darwin_arm64.tar.gz"
      sha256 "2d2484678b4fa5340a45b611259e5fb52a8fa61f78393d5380f4522017faab8c"

      def install
        bin.install "barebones"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.4.6/barebones_0.4.6_linux_amd64.tar.gz"
      sha256 "e05646af5bab2367b68ae861d59ebf4485e1c5c7806fd4efb97406d74e034392"
      def install
        bin.install "barebones"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexlokshin/barebones/releases/download/v0.4.6/barebones_0.4.6_linux_arm64.tar.gz"
      sha256 "326ec6b39c95f5cf80925a3b6af4edfe15d3493af10d1b4e93c1b4e40fdd8788"
      def install
        bin.install "barebones"
      end
    end
  end

  test do
    system "#{bin}/barebones", "-health-check"
  end
end
